services:
  postgres:
    image: postgres:15-alpine
    container_name: loadtest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loadtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  back-go:
    build:
      context: ./back-go
      dockerfile: Dockerfile
    container_name: loadtest-back-go
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/loadtest?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
