services:
  postgres:
    image: postgres:15-alpine
    container_name: loadtest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loadtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  back-python:
    build:
      context: ./back-python
      dockerfile: Dockerfile
    container_name: loadtest-back-python
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/loadtest"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: loadtest-frontend
    ports:
      - "3000:80"
    depends_on:
      - back-python

volumes:
  postgres_data:
